### ISSUE TITLE
신고하겠습니다

### ISSUE THREAD

**Issue by Jun99uu** [likelion-ssu/2023_BE-SSION#1]
아니 저희는 쀄ㅔㅔㅔ션이라는 이름으로 지은건데 붸ㅔㅔㅔ션은 뭔가요?

**Comment by Song-EunJu** [comment]
@Jun99uu  우리 귀요미한테 뭐라고 하지마세요

**Comment by Jun99uu** [comment]
@Song-EunJu 
?? : 아 어제 예림이한테 스톤 얻어먹으려다가 돈달라고 연락와서 실패함ㅠ

**Comment by yel-m** [comment]
두 분 완만한 합의 바라겟습니다

**Comment by Song-EunJu** [comment]
정예림씨가 책임지세요

**Comment by yel-m** [comment]
@Song-EunJu 
책임은 '송은주 책임'님 담당이라 잘 모르겟군요

**Comment by Jun99uu** [comment]
송은 주책이야

**Comment by yoo-jimin127** [comment]
@Song-EunJu 우리 귀요미한테 뭐라고 하지 마세요
